### ISSUE TITLE
Замечания по 3 лабе

### ISSUE THREAD

**Issue by nekosyakolyastudy** [nekosyakolya/aisd#2]
- [x] запретить перемещение корня

**Comment by nekosyakolyastudy** [comment]
- [x] после удаления корня сообщение об ошибке

**Comment by nekosyakolyastudy** [comment]
- [x] при копировании косяк с пересчетом уровней

**Comment by nekosyakolyastudy** [comment]
- [x] защита на конец файла при вводе нового имени

**Comment by nekosyakolyastudy** [comment]
- [x] выводить сообщение,что нажатие на End- выход из программы

**Comment by nekosyakolyastudy** [comment]
- [x] при вставке проверять объект на пустоту

**Comment by denis-afanasev** [comment]
![image](https://cloud.githubusercontent.com/assets/22054194/21293947/30dffc16-c543-11e6-959a-87978945d5c4.png)

- [x] создание папки/файла рядом с корнем приводит к неопределенному поведению
